[@Ultra]

[Header]
;version= 23|A3
;creator= redraz
;about= Multitool for UltraNX
;credits= Thanks to ppkantorski, Soul & Lightos

;color=#6600FF
;show_widget=true

;HOC=1.2.1
;tuner=test



;mode=table
;background=false
;gap=17
;header_indent=true
'Info' = ''




[Info]
;mode=table
;spacing=1
;gap=0
'Creator'= 'redraz'
'Telegram Group'= 't.me/UltraNX'
' ' = ''
'About'= 'Multitool for overclocking,'
' ' = 'changing system settings'
' ' = '& downloading homebrews'




[Gap]
;mode=table
;background=false
;gap=30

[Header]
;mode=table
;background=false
;header_indent=true
;polling=true
;gap=17
ini_file '/switch/.packages/Ultra Tuner/package.ini'
'Loader OC'= 'Horizon OC {ini_file(Header,;HOC)}'

[*Tuning]
;mode=forwarder
package_source './Data/Tuner/Tuner.ini'





[Gap]
;mode=table
;background=false
;gap=20

[Header]
;mode=table
;background=false
;header_indent=true
;gap=17
'Downloads'= 'Other {DRIGHT}'

[*Updater]
;mode=forwarder
package_source './Data/Updater/Updater.ini'
exec update


[*Software]
;mode=forwarder
package_source './Data/Updater/Software.ini'


[*Mods]
;mode=forwarder
package_source './Data/Updater/Mods.ini'




















[@Other]


[Info]
;mode=table
;background=false
;gap=17
'Atmosphere'='Reboot to apply'


[*Fan Curves]
;mode=forwarder
package_source './Data/Updater/Curves Manager.ini'

cp '/config/UltraNX/curves.ini' './Data/Updater/config.ini'





[GPU Scheduling]
;mode=toggle
;mini=true
on:
   set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x1
off:
   set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x0


[USB 3.0 Support]
;mode=toggle
;mini=true
on:
   set-ini-val /atmosphere/config/system_settings.ini usb usb30_force_enabled u8!0x1
off:
   set-ini-val /atmosphere/config/system_settings.ini usb usb30_force_enabled u8!0x0


[Crash Autoreboot]
;mode=toggle
;mini=true
on:
   set-ini-val /atmosphere/config/system_settings.ini atmosphere fatal_auto_reboot_interval u64!0x3000
off:
   set-ini-val /atmosphere/config/system_settings.ini atmosphere fatal_auto_reboot_interval u64!0x0



[Gap]
;mode=table
;background=false
;gap=10

[Info]
;mode=table
;background=false
;gap=15
'Video Capture' = ''

[Framerate]
;mode=named_step_trackbar
;unlocked=false
json_source '[{"name":"30 FPS", "value":"u32!30"}, {"name":"60 FPS", "value":"u32!60"}]' name
set-ini-val /atmosphere/config/system_settings.ini am.debug continuous_recording_fps {json_source(*,value)}


[Bitrate]
;mode=named_step_trackbar
;unlocked=false
json_source '[{"name":"5.9 Mbs [30s]", "value":"u32!0x5A06E0"}, {"name":"9.2 Mbs [20s]", "value":"u32!0x8C6180"}, {"name":"13 Mbs [15s]", "value":"u32!0xC65D40"}, {"name":"20 Mbs [10s]", "value":"u32!0x1312D00"}]' name
set-ini-val /atmosphere/config/system_settings.ini am.debug continuous_recording_video_bit_rate {json_source(*,value)}



[Gap]
;mode=table
;background=false
;gap=10

[Info]
;mode=table
;background=false
;gap=15
'Charging' = ''

[Charge Speed]
;mode=named_step_trackbar
;unlocked=false
json_source '[{"name":"[Slow]             1536mA", "value":"u32!0x600"}, {"name":"[Default]              Stock", "command":"remove-ini-key", "value":"0"}, {"name":"[Normal]         2144mA", "value":"u32!0x860"}, {"name":"[Fast]              2560mA", "value":"u32!0xA00"}, {"name":"[Ultra]             3072mA", "value":"u32!0xC00"}]' name
set-ini-val /atmosphere/config/system_settings.ini psm charge_current_limit_milli_ampere {json_source(*,value)}
{json_source(*,command)} /atmosphere/config/system_settings.ini psm charge_current_limit_milli_ampere







[Gap]
;mode=table
;background=false
;gap=20

[Header]
;mode=table
;background=false
;header_indent=true
;gap=17
'Status Monitor'= 'ppkantorski fork only'

[*Preset Micro]
;mode=option
;mini=true
json_file_source './Data/Updater/Monitor Preset.json' name

set-ini-val /config/status-monitor/config.ini micro handheld_font_size {json_file_source(*,font)}
set-ini-val /config/status-monitor/config.ini micro docked_font_size {json_file_source(*,font)}
set-ini-val /config/status-monitor/config.ini micro text_align {json_file_source(*,align)}
set-ini-val /config/status-monitor/config.ini micro real_freqs {json_file_source(*,freqs)}
set-ini-val /config/status-monitor/config.ini micro real_volts {json_file_source(*,volts)}
set-ini-val /config/status-monitor/config.ini micro show {json_file_source(*,show)}
set-ini-val /config/status-monitor/config.ini micro show_full_cpu {json_file_source(*,cpu)}
set-ini-val /config/status-monitor/config.ini micro show_full_res {json_file_source(*,res)}
set-ini-val /config/status-monitor/config.ini micro background_color {json_file_source(*,back)}
set-ini-val /config/status-monitor/config.ini micro separator_color {json_file_source(*,sep)}
set-ini-val /config/status-monitor/config.ini micro cat_color {json_file_source(*,cat)}
set-ini-val /config/status-monitor/config.ini micro text_color {json_file_source(*,text)}

set-ini-val /config/status-monitor/config.ini status-monitor preset {json_file_source(*,label)}
set-footer {json_file_source(*,label)}
back







[Gap]
;system=mariko
;mode=table
;background=false
;gap=20

[Header]
;system=mariko
;mode=table
;background=false
;header_indent=true
;gap=17
'Other'= ''


[*Select RAM]
;mode=option
;mini=true
json_file_source './Data/Updater/ram.json' name

set-ini-val '/switch/.packages/Ultra Tuner/config.ini' '*Select RAM' vendor {json_file_source(*,vendor)}
set-ini-val '/switch/.packages/Ultra Tuner/config.ini' '*Select RAM' model {json_file_source(*,model)}
set-ini-val '/switch/.packages/Ultra Tuner/config.ini' '*Select RAM' value {json_file_source(*,value)}

set-footer {json_file_source(*,model)}
{json_file_source(*,autoram)} autoram

set-ini-val /config/UltraNX/Tuner.ini RAM vendor {json_file_source(*,vendor)}
set-ini-val /config/UltraNX/Tuner.ini RAM model {json_file_source(*,model)}
set-ini-val /config/UltraNX/Tuner.ini RAM mode {json_file_source(*,value)}

back


[OC Autobackup]
;mode=toggle
;mini=true
on:
	set-ini-val ./config.ini 'OC Autobackup' value Autobackup
   set-ini-val /config/UltraNX/Tuner.ini Autobackup value Autobackup

off:
	set-ini-val ./config.ini 'OC Autobackup' value Nobackup
   set-ini-val /config/UltraNX/Tuner.ini Autobackup value Nobackup







[Gap]
;system=mariko
;mode=table
;background=false
;gap=20

[Header]
;system=mariko
;mode=table
;background=false
;header_indent=true
;gap=17
'Memory Patch'= ''


[Info]
;mode=table
;spacing=6
' ' = 'Breaks the browser                                        '
' ' = 'and games dependent on it                            '
' ' = 'but fixes the old mods                                    '


[Gap]
;mode=table
;background=false
;gap=17



[+40MB System Patch]
;try
;system=mariko
;mode=toggle
on:
   cp '/switch/.packages/Ultra Tuner/Data/Updater/mesosphere.bin' /atmosphere/mesosphere.bin
   set-ini-val-matching-key /bootloader/hekate_ipl.ini cal0blank kernel atmosphere/mesosphere.bin
   remove-ini-key /bootloader/hekate_ipl.ini 'Safe Mode' kernel
   set-ini-val /config/UltraNX/Tuner.ini 40MB patch On
   
off:
   del /atmosphere/mesosphere.bin
   remove-ini-key-matching-key /bootloader/hekate_ipl.ini cal0blank kernel
   set-ini-val /config/UltraNX/Tuner.ini 40MB patch Off